version: '3.7'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        BACKEND_BASE_URL: ${BACKEND_BASE_URL}
    ports:
      - 3000:3000
    restart: always
    env_file:
      - ./frontend/.env
